/**
 * 🎨 ألوان Tailwind — تقرأ من css/tokens.css فقط
 * @see css/tokens.css
 */
tailwind.config = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary': 'var(--color-on-secondary)',
        'error-container': 'var(--color-error-container)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-surface': 'var(--color-on-surface)',
        'surface': 'var(--color-surface)',
        'outline-variant': 'var(--color-outline-variant)',
        'surface-tint': 'var(--color-surface-tint)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'primary-container': 'var(--color-primary-container)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'tertiary': 'var(--color-tertiary)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'on-error-container': 'var(--color-on-error-container)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'background': 'var(--color-background)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'primary': 'var(--color-primary)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'surface-variant': 'var(--color-surface-variant)',
        'surface-container': 'var(--color-surface-container)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'surface-bright': 'var(--color-surface-bright)',
        'secondary-container': 'var(--color-secondary-container)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'secondary': 'var(--color-secondary)',
        'on-background': 'var(--color-on-background)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'on-error': 'var(--color-on-error)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'on-primary': 'var(--color-on-primary)',
        'surface-dim': 'var(--color-surface-dim)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'outline': 'var(--color-outline)',
        'error': 'var(--color-error)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'dm-bg': 'var(--dm-bg)',
        'dm-surface': 'var(--dm-surface)',
        'dm-elevated': 'var(--dm-elevated)',
        'dm-elevated-2': 'var(--dm-elevated-2)',
        'dm-border': 'var(--dm-border)',
        'dm-text': 'var(--dm-text)',
        'dm-text-muted': 'var(--dm-text-muted)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        base: '4px',
        'container-max': '1280px',
        md: '16px',
        xl: '48px',
        gutter: '24px',
        sm: '8px',
        lg: '24px',
      },
      fontFamily: {
        'headline-md': ['Noto Naskh Arabic', 'Source Serif 4', 'serif'],
        'label-md': ['Noto Naskh Arabic', 'Source Serif 4', 'serif'],
        'display-lg': ['Noto Naskh Arabic', 'Source Serif 4', 'serif'],
        'body-md': ['Noto Naskh Arabic', 'Source Serif 4', 'serif'],
        'display-lg-mobile': ['Noto Naskh Arabic', 'Source Serif 4', 'serif'],
        'body-lg': ['Noto Naskh Arabic', 'Source Serif 4', 'serif'],
        'code-sm': ['JetBrains Mono', 'monospace'],
        'headline-sm': ['Noto Naskh Arabic', 'Source Serif 4', 'serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '36px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '500' }],
        'display-lg': ['40px', { lineHeight: '56px', fontWeight: '700' }],
        'body-md': ['17px', { lineHeight: '30px', fontWeight: '400' }],
        'display-lg-mobile': ['24px', { lineHeight: '36px', fontWeight: '700' }],
        'body-lg': ['19px', { lineHeight: '34px', fontWeight: '400' }],
        'code-sm': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '32px', fontWeight: '600' }],
      },
    },
  },
};
